language: generic

sudo: false

git:
  submodules: false

cache:
  directories:
    - $HOME/.mafia

matrix:
  include:
  - env: GHCVER=8.4.4 CABALVER=2.0
    addons:
      apt:
        sources:
          - hvr-ghc
        packages:
          - ghc-8.4.4
          - cabal-install-2.0

  # mafia doesn't build with 8.4.2 yet...
  #- env: GHCVER=8.4.2 CABALVER=1.24
  #  addons:
  #    apt:
  #      sources:
  #        - hvr-ghc
  #      packages:
  #        - ghc-8.4.2
  #        - cabal-install-1.24

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  # ghc
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

script:
  - timeout 30m bin/ci
